language: go

go:
  - "1.10.x"

install:
  - echo "===== Clone registry ====="
  - git clone https://github.com/just-install/registry

script:
  - echo "==== Unit tests ====="
  - go test -v ./...
  - echo "===== Reachability test ====="
  - go run jiup/rules/reachability-test/main.go

# deploy:
#   - provider: script
#     script:
#       - echo "===== Update registry ====="
#       - go run main.go registry/just-install.json
#       - echo "==== Push registry to GitHub ====="
#       - cd registry
#       - 'git status --porcelain || echo "===== No changes to push ====="'
#       - 'git status --porcelain && {git add -A ; git commit -m "automatic update" ; git push}'
#     on:
#       branch: master