language: go

go:
  - "1.10.x"

install:
  - echo "===== Clone registry =====" ; git clone https://github.com/just-install/registry

script:
  - echo "==== Unit tests =====" ; go test -v ./...
  - echo "===== Reachability test =====" ; go run jiup/rules/reachability-test/main.go

deploy:
  - provider: script
    script:
      - echo "machine github.com" > ~/.netrc
      - echo "login github.com" >> ~/.netrc
      - echo "password $GITHUB_TOKEN" >> ~/.netrc
      - git config --global user.name "just-install-bot"
      - git config --global user.email "just-install-bot@outlook.com"
      - go run main.go registry/just-install.json
      - cd registry
      - git add -A || true
      - git commit -m "jiup-go automatic commit" || true
      - git push
    on:
      branch: master