language: go

go:
  - "1.10.x"

install:
  - echo "===== Clone registry =====" ; git clone https://github.com/just-install/registry

script:
  - echo "==== Unit tests =====" ; go test -v ./...
  - echo "===== Reachability test =====" ; go run jiup/rules/reachability-test/main.go

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - bash deploy.sh
    on:
      branch: master