language: go

go:
  - "1.10.x"

install:
  - echo "===== Clone registry =====" ; git clone https://github.com/just-install/registry

script:
  - echo "==== Unit tests =====" ; go test -v ./...
  - echo "===== Reachability test =====" ; go run jiup/rules/reachability-test/main.go

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - echo "machine github.com" > ~/.netrc
      - echo "login $GITHUB_TOKEN" >> ~/.netrc
      - echo "password x-oauth-basic" >> ~/.netrc
      - git config --global user.name "just-install-bot"
      - git config --global user.email "just-install-bot@outlook.com"
      - go run main.go registry/just-install.json
      - git status -C registry || true
      - git add -A -C registry || true
      - git commit -m "jiup-go automatic commit" -C registry || true
      - git push -C registry
    on:
      branch: master